# Generated by Django 4.2.2 on 2023-06-23 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dream'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordedDays', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
