# Generated by Django 4.2.2 on 2023-06-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recordeddays'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AlterField(
            model_name='dream',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dream',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
