# Generated by Django 4.2.2 on 2023-06-30 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_task_alter_dream_desc_alter_dream_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_entries_per_page_setting',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='RecordedDays',
        ),
    ]
